---

# Run the playbook using:
# ansible-playbook -i localhost, r-ci.yml

# Use raw to disable tag processing {% raw %}

- name: Run the playbook to check the package
  hosts: localhost
  connection: local

  tasks:
  - name: Determine the package name from the DESCRIPTION file
    ansible.builtin.command:
      cmd: >
        Rscript --vanilla
        -e "x <- tryCatch(read.dcf('DESCRIPTION')[, 'Package'], error = function(e) NULL)"
        -e "if (is.null(x)) quit(save = 'no', status = 1, runLast = FALSE)"
        -e "cat(x)"
      chdir: "{{ lookup('env', 'PWD') }}"
    register: pkg_name
    changed_when: false
    become: false

  - name: Determine the package version from the DESCRIPTION file
    ansible.builtin.command:
      cmd: >
        Rscript --vanilla
        -e "x <- tryCatch(read.dcf('DESCRIPTION')[, 'Version'], error = function(e) NULL)"
        -e "if (is.null(x)) quit(save = 'no', status = 1, runLast = FALSE)"
        -e "cat(x)"
      chdir: "{{ lookup('env', 'PWD') }}"
    register: pkg_version
    changed_when: false
    become: false

  - name: Determine the name of the built package
    ansible.builtin.command:
      cmd: "echo {{ pkg_name.stdout }}_{{ pkg_version.stdout }}.tar.gz"
    register: pkg_tar
    changed_when: false
    become: false

  - name: Display package information
    ansible.builtin.debug:
      msg:
        - "Package name: {{ pkg_name.stdout }}"
        - "Package version: {{ pkg_version.stdout }}"
        - "Package file: {{ pkg_tar.stdout }}"
    become: false

  - name: Build the package
    ansible.builtin.command:
      cmd: "R CMD build --no-manual --compact-vignettes=both ."
      chdir: "{{ lookup('env', 'PWD') }}"
    register: pkg_build_log
    changed_when: false
    become: false

  - name: Display the package build log
    ansible.builtin.debug:
      msg: "{{ pkg_build_log.stdout_lines }}"
    become: false

  - name: Check the package
    ansible.builtin.command:
      cmd: "R CMD check --no-stop-on-test-error --as-cran {{ pkg_tar.stdout }}"
      chdir: "{{ lookup('env', 'PWD') }}"
    environment:
      _R_CHECK_CRAN_INCOMING_: false
    register: pkg_check
    changed_when: false
    failed_when: false
    become: false

  - name: Read the package check log
    ansible.builtin.command:
      cmd: "cat {{ pkg_name.stdout }}.Rcheck/00check.log"
      chdir: "{{ lookup('env', 'PWD') }}"
    register: pkg_check_log
    changed_when: false

  - name: Display the package check log
    ansible.builtin.debug:
      msg: "{{ pkg_check_log.stdout_lines }}"
    failed_when: pkg_check.rc != 0 or "WARNING" in pkg_check_log.stdout
    become: false

# {% endraw %}
